/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package transportmanagementsystem.presentation;

/**
 *
 * @author Rising Star
 */

import javax.swing.*;
import transportmanagementsystem.model.Payment;
import transportmanagementsystem.repository.BookingRepository;
import transportmanagementsystem.repository.PaymentRepository;
import transportmanagementsystem.repository.TransactionRepository;
import transportmanagementsystem.controller.PaymentController;

public class PaymentProcess extends javax.swing.JFrame {
 private int bookingId;
    private PaymentController controller;
    /**
     * Creates new form PaymentProcess
     */
    public PaymentProcess() {
        initComponents();
    }
  public PaymentProcess(String customerName, int bookingId, PaymentController controller) {
        this.bookingId = bookingId;
        this.controller = controller;
        initComponents();
        txtname.setText(customerName);
        txtname.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtpaymentmethod = new javax.swing.JTextField();
        txtamount = new javax.swing.JTextField();
        txtphoneno = new javax.swing.JTextField();
        txtcode = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("PAYMENT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 58, 136, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("PAYMENT METHOD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 111, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("AMOUNT");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 174, 217, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("PHONE NO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 230, 208, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("CODE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 286, 87, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("EMAIL");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 342, 87, -1));

        txtname.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 55, 277, -1));

        txtpaymentmethod.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(txtpaymentmethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 111, 277, -1));

        txtamount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 171, 277, -1));

        txtphoneno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtphoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphonenoActionPerformed(evt);
            }
        });
        getContentPane().add(txtphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 227, 277, -1));

        txtcode.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(txtcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 283, 277, -1));

        txtemail.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 339, 277, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 130, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 110, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtphonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphonenoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     handleSubmit(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         handleClear(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

  private void handleSubmit(java.awt.event.ActionEvent evt) {
        try {
            Payment payment = new Payment();
            payment.setBookingId(bookingId);
            payment.setName(txtname.getText());
            payment.setPaymentMethod(txtpaymentmethod.getText());
            payment.setAmount(Double.parseDouble(txtamount.getText()));
            payment.setPhoneNo(txtphoneno.getText());
            payment.setCode(txtcode.getText());
            payment.setEmail(txtemail.getText());

            int paymentId = PaymentRepository.savePayment(payment);

           if (paymentId != -1) {
    int option = JOptionPane.showConfirmDialog(
        this,
        "Do you want to save this transaction in the database?",
        "Save Transaction",
        JOptionPane.YES_NO_OPTION
    );

    if (option == JOptionPane.YES_OPTION) {
        TransactionRepository.saveTransaction(paymentId);
        JOptionPane.showMessageDialog(this, "✅ Transaction saved successfully.");
    } else {
        JOptionPane.showMessageDialog(this, "ℹ Transaction not saved.");
    }

    BookingRepository.markBookingAsPaid(bookingId);

    JOptionPane.showMessageDialog(this, "✅ Payment marked as Paid.");
    if (controller != null) controller.loadUnpaidBookings();
    dispose();
}
 
            else {
                JOptionPane.showMessageDialog(this, "❌ Failed to save payment.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "⚠ Error: " + e.getMessage());
        }
    }

    private void handleClear(java.awt.event.ActionEvent evt) {
        txtpaymentmethod.setText("");
        txtamount.setText("");
        txtphoneno.setText("");
        txtcode.setText("");
        txtemail.setText("");
    }




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentProcess("Test User", 1, null).setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtcode;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpaymentmethod;
    private javax.swing.JTextField txtphoneno;
    // End of variables declaration//GEN-END:variables
}
